/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/Child/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Parent: typeof import('./src/components/Parent/index.vue')['default']
    Remote: typeof import('./src/components/Remote/index.vue')['default']
  }
}
