packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'examples/*'
  # all packages in subdirs of components/
  - 'apps/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
